const example = {
  exemptions: {
    totalDerechos: true,
    separacionCarga: true,
    obligacionesFiscales: true,
    servicioConsolidadoMaritimo: true,
  },
  dynamicValues: {
    kg: 350,
    kv: 0,
    cif: 1164,
    fob: 889,
    ton: 0.35,
    cajas: 8,
    flete: 250,
    seguro: 25,
    igvRate: 16,
    ipmRate: 2,
    iscRate: 0,
    nroBultos: 8,
    tipoCambio: 3.75,
    volumenCBM: 2.5,
    desaduanaje: 150,
    calculoFlete: 250,
    adValoremRate: 4,
    comercialValue: 889,
    otrosServicios: 0,
    percepcionRate: 3.5,
    separacionCarga: 30,
    transporteLocal: 80,
    inspeccionFabrica: 0,
    shouldExemptTaxes: false,
    gestionCertificado: 0,
    inspeccionProducto: 0,
    antidumpingCantidad: 0,
    antidumpingGobierno: 0,
    inspeccionProductos: 0,
    servicioConsolidado: 120,
    transporteLocalChinaEnvio: 50,
    transporteLocalClienteEnvio: 80,
  },
  serviceCalculations: {
    totals: { inversionTotal: 1548.88 },
    igvServices: 27,
    serviceFields: {
      separacionCarga: 30,
      inspeccionProductos: 0,
      servicioConsolidado: 120,
    },
    totalServices: 177,
    importExpenses: {
      separacionCargaFinal: 35.4,
      totalGastosImportacion: 659.88,
      servicioConsolidadoFinal: 141.6,
    },
    subtotalServices: 150,
    fiscalObligations: { adValorem: 46.56, totalDerechosDolares: 255.88 },
  },
};
